"""add user answer + total score

Revision ID: 1255be3a8823
Revises: 8d4a9baaa591
Create Date: 2023-04-26 17:00:33.997582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1255be3a8823'
down_revision = '8d4a9baaa591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
