"""add decriptions + relatiships

Revision ID: 1dbf30ec1ee8
Revises: be4113431f2a
Create Date: 2023-04-26 16:16:36.195636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbf30ec1ee8'
down_revision = 'be4113431f2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_decription', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'answer', 'task', ['id_task'], ['id'])
    op.create_foreign_key(None, 'task', 'olimpiad', ['id_olimpiad'], ['id'])
    op.create_foreign_key(None, 'task', 'module', ['module'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_table('decriptions')
    # ### end Alembic commands ###
