"""add decriptions + relatiships

Revision ID: 57dfc9d198ce
Revises: 1dbf30ec1ee8
Create Date: 2023-04-26 16:27:23.496628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57dfc9d198ce'
down_revision = '1dbf30ec1ee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('decription', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'decriptions', ['description_id'], ['id'])
    op.create_foreign_key(None, 'task', 'decriptions', ['decription'], ['id'])
    op.create_foreign_key(None, 'task', 'type_task', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'decription')
    op.drop_table('type_task')
    # ### end Alembic commands ###
