"""add user answer + total score

Revision ID: 79bc8060646c
Revises: e3f02ebec2ac
Create Date: 2023-04-26 20:34:37.740738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bc8060646c'
down_revision = 'e3f02ebec2ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
