"""add user answer + total score

Revision ID: 8d4a9baaa591
Revises: d7a0be7330f0
Create Date: 2023-04-26 16:55:40.953839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4a9baaa591'
down_revision = 'd7a0be7330f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('total_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_olimpiad', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_olimpiad'], ['olimpiad.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('task_description_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'description_id')
    op.add_column('user_answer', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('user_answer', 'id')
#     op.add_column('task', sa.Column('description_id', sa.INTEGER(), autoincrement=False, nullable=True))
#     op.create_foreign_key('task_description_id_fkey', 'task', 'decriptions', ['description_id'], ['id'])
#     op.drop_table('total_score')
    # ### end Alembic commands ###
