"""add user answer + total score

Revision ID: cbb9eb5c5350
Revises: 79bc8060646c
Create Date: 2023-04-26 20:36:16.386893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb9eb5c5350'
down_revision = '79bc8060646c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
