"""add user answer + total score

Revision ID: d7a0be7330f0
Revises: 57dfc9d198ce
Create Date: 2023-04-26 16:51:19.665493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a0be7330f0'
down_revision = '57dfc9d198ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_answer',
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_task', sa.Integer(), nullable=True),
    sa.Column('id_answer', sa.Integer(), nullable=True),
    sa.Column('id_olimpiad', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_answer'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['id_olimpiad'], ['olimpiad.id'], ),
    sa.ForeignKeyConstraint(['id_task'], ['task.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    # op.create_table('total_score',
    # sa.Column('id_user', sa.Integer(), nullable=True),
    # sa.Column('id_olimpiad', sa.Integer(), nullable=True),
    # sa.Column('total_score', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['id_olimpiad'], ['olimpiad.id'], ),
    # sa.ForeignKeyConstraint(['id_user'], ['user_answer.id_user'], )
    # )
    # op.drop_constraint('task_description_id_fkey', 'task', type_='foreignkey')
    # op.drop_column('task', 'description_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('description_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_description_id_fkey', 'task', 'decriptions', ['description_id'], ['id'])
    op.drop_table('total_score')
    op.drop_table('user_answer')
    # ### end Alembic commands ###
