"""add user answer + total score

Revision ID: e3f02ebec2ac
Revises: 9cba0f2a3fc3
Create Date: 2023-04-26 20:33:39.539188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f02ebec2ac'
down_revision = '9cba0f2a3fc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
