"""User11

Revision ID: e57e3d7a2c24
Revises: f536488ceba0
Create Date: 2023-04-23 00:55:30.861254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57e3d7a2c24'
down_revision = 'f536488ceba0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
