"""add user answer + total score

Revision ID: f9bf3ad6144f
Revises: cbb9eb5c5350
Create Date: 2023-05-12 16:06:24.739305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bf3ad6144f'
down_revision = 'cbb9eb5c5350'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_in_olimpiad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_olimpiad', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_olimpiad'], ['olimpiad.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_in_olimpiad')
    # ### end Alembic commands ###
